jenkins:
  systemMessage: "Testing\n\n"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
      
jobs:
  - script: >
      pipelineJob('pipeline') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/albertnoble/ExampleNet.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      }

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "a8ee1ede-5a52-4b53-bb6b-02e4b5e97cd2"
          password: "{AQAAABAAAAAQ1vUEl/e6Hv8QriBTa5a72kj/yw0acPamEU3IuW2oSjI=}"
          scope: GLOBAL
          username: "albertnoble"
      - usernamePassword:
          id: "604291b7-42de-42ee-b771-d14fa78f06c0"
          password: "{AQAAABAAAAAQPaykPz1wIt9pT5nk1gsL3PCSeoILJJFTGl7tWJ5AyOc=}"
          scope: GLOBAL
          username: "administrator" 

jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"

# plugins:
#   required:
#     blueocean: latest
#     workflow-aggregator: latest
#     pipeline-maven: latest
#     configuration-as-code-support: latest
#     job-dsl: latest
